pr:
  branches:
    include:
      - dev
  paths:
    include:
      - DataAccessInterface

trigger:
  branches:
    include:
    - dev
  paths:
    include:
      - DataAccessInterface

pool:
  vmImage: 'windows-2019'

variables:
  solution: 'DataAccessInterface/DataAccessInterface.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0
  inputs:
    versionSpec: '4.9.2'

- task: MSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: ResharperCli@2
  inputs:
    solutionOrProjectPath: '$(solution)' 

- task: NuGetCommand@2
  inputs:
    command: pack
    basePath: $(Build.SourcesDirectory)/DataAccessInterface/DataAccessInterface/bin/release
    packagesToPack: $(Build.SourcesDirectory)/DataAccessInterface/DataAccessInterface.nuspec
    packDestination: $(Build.StagingDirectory)\NuGetPackage

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.StagingDirectory)\NuGetPackage
    ArtifactName: 'NuGetPackage'
    publishLocation: Container

